### ISSUE TITLE
"Updated" Column not Updated

### ISSUE THREAD

**Issue by luke-** [humhub/cfiles#146]
With modules like "OnlyOffice" or "Text-Editor" the file content is updated directly. but in the CFiles column "Updated" this is not updated.

We should either show there the "Updated" of the underlying file, or update the CFile record as well (via an event?) when the file is changed.

![image](https://user-images.githubusercontent.com/4736168/143920002-5c52011c-b6bb-481f-8d52-587ae56d85ec.png)

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/cfiles/pull/148:

I implemented this way "*update the CFile record as well (via an event?) when the file is changed.*".

**Comment by luke-** [comment]
@yurabakhtin Is the event correctly triggered here? 
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/file/models/File.php#L356

**Comment by yurabakhtin** [comment]
@luke- Yes, the code is executed correctly there, but please note there the fields are updated in the table `file`. However on the Cfiles table-list we display column `Updated` data from the table `content`. It is why I create an additional event in order to update fields of the object `CFile->content`.

**Comment by luke-** [comment]
@yurabakhtin Yes, but the `file` table is modified using `updateAttributes`, which not triggers events?

**Comment by yurabakhtin** [comment]
@luke- Yes the `updateAttributes()` doesn't trigger any event because it calls a static method `ActiveRecord::updateAll(...)`.

It seems you want to say we should call the new code https://github.com/humhub/cfiles/pull/148/files#diff-666c020a6d1e6a59ba261ba9316aaa19e27dbd851bcc4fdcaecaa278ddc96c10R176-R190 not on the event `File::EVENT_AFTER_UPDATE` but we should call this inside the method `File->afterNewStoredFile()`, right?
If yes, then we can create a new trigger right inside the method `File->afterNewStoredFile()` with code like `$this->trigger(self::EVENT_AFTER_NEW_STORED_FILE)`. Do you mean this by your questions?

**Comment by luke-** [comment]
@yurabakhtin I think we need to either create/trigger a new event here **or** just use a `save()` to trigger the standard save event. I would rather prefer the second option, the standard `save()` event.

Do you see any problems here?

**Comment by yurabakhtin** [comment]
@luke- 

> Do you see any problems here?

I see a possible infinite recursion because the `File->setStoredFile()` is called from `FileUpload::afterSave()` - https://github.com/humhub/humhub/blob/master/protected/humhub/modules/file/models/FileUpload.php#L49, i.e. steps of the calling is:

- `FileUpload::save()`, note: `class FileUpload extends File`
  - `FileUpload::aftersSave()`
    - `File::setStoredFile()`
       - `File::afterNewStoredFile()` <- here we call `File->updateAttributes()` currently, but if we will call `$this->save()` then the `FileUpload::save()` will be called twice, however on the second call I see there `$this->store->has() === false` so no infinite recursion, but I am not sure it will works well for all unknown cases even if I could not reproduce the infinite loop.

Is it clear why I am afraid to use `File->save()` there? If yes, do you agree to create a new event inside `File->afterNewStoredFile()`?

**Comment by luke-** [comment]
@yurabakhtin Ok, then let's introduce an new Event and use this. Thanks for the clarification! :-)

**Comment by yurabakhtin** [comment]
@luke- Core PR https://github.com/humhub/humhub/pull/5461, Commit for this module PR https://github.com/humhub/humhub/pull/5461.

**Comment by luke-** [comment]
@yurabakhtin Looks good! Can you please base the Core PR against Master.

**Comment by yurabakhtin** [comment]
@luke- 

> Can you please base the Core PR against Master.

I did this by changing base from `develop` to `master` but we don't need changes here https://github.com/humhub/humhub/pull/5461/files in the files:

- CHANGELOG_DEV.md
- protected/humhub/messages/de/archive.json 
- protected/humhub/modules/tour/resources/js/humhub.tour.js
- protected/humhub/modules/user/models/User.php

Do you know a quick way to revert the changes there? If no then I should again to create a new PR from the `master` branch and apply the changes, but it would be better to know what source branch I should use before start a new PR.

**Comment by yurabakhtin** [comment]
@luke- I see you merged the PR, but please note we don't need the changes in the file https://github.com/humhub/humhub/pull/5461/files#diff-a3580050a877b1341c72bd00e0cf540a59eaa32b67e217d0e574924894fb6571 `protected/humhub/messages/de/archive.json`. I tried to revert the changes manually in the commit https://github.com/humhub/humhub/pull/5461/commits/00492ed786b08067d3ec79778bab3dc36426b446 but it seems it didn't, probably they will be fixed later automatically somehow or please fix that if you know how, thanks.

**Comment by luke-** [comment]
Ok, no worry about `archive.json" it's just an internal file for the translation site. We can ignore this.
Anything else ok with the Core Master Merge?

Regarding the CFile PR, i see errors in the test: https://github.com/humhub/cfiles/pull/148/checks - The CFiles Master Branch seems to be ok.

**Comment by yurabakhtin** [comment]
@luke- 

> Anything else ok with the Core Master Merge?

Yes, other conflicts were fixed.

> Regarding the CFile PR, i see errors in the test: https://github.com/humhub/cfiles/pull/148/checks - The CFiles Master Branch seems to be ok.

The tests cannot be executed on `develop` branch because there is no new event `File:: EVENT_AFTER_NEW_STORED_FILE`, so I disabled it here https://github.com/humhub/cfiles/pull/148/commits/9be1cb08eb6182eea4a9ed0f9a1dc302a0aa4967 but after that I see  errors not clear for me, because I cannot reproduce them on my local server. I could fix them only in 2 commits https://github.com/humhub/cfiles/pull/148/commits/4e09b75aa7e4014cbe0c81dbea11084e5dbb178c, https://github.com/humhub/cfiles/pull/148/commits/a5e7d2b92eb322e6c2c379e1c1701ca09f083412.

**Comment by aaukt** [comment]
@luke- @yurabakhtin 
Am i right in thinking that the OnlyOffice module does not use this fixed implementation because it avoids calling `File::setStoredFileContent()` and instead sets the content directly via the store here: https://github.com/ONLYOFFICE/onlyoffice-humhub/blob/master/controllers/BackendController.php#L123 ?

Because right now it seems onlyoffice still does not update the "updated" column.

Should i file an issue against the onlyoffice module to use the "official" method or would it actually be better if the  EVENT_AFTER_NEW_STORED_FILE is triggered in the StoreManager component?

**Comment by luke-** [comment]
@aaukt Should be already fixed in the `develop` branch:
https://github.com/ONLYOFFICE/onlyoffice-humhub/blob/develop/controllers/BackendController.php#L147

**Comment by aaukt** [comment]
@luke- Nice, thank you for the info.
