### ISSUE TITLE
Doesn't work since HH1.14

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub/cfiles#179]
Steps to reproduce:
Clean fresh HH installation:
**HH1.13 + Files 0.15.1**
Allow files module in a public space
Add public files
It works! I can upload files, see and download them. so far so good.

**HH1.14.0 + Files 0.15.1**
Same settings as before
Doesn’t work. I can upload files, but **cannot see or download them**. Instead I get an error 
![image](https://github.com/humhub/cfiles/assets/91057837/2b1aaa81-d132-4379-b89b-bdd2d36e4d3d)
Notice: I can still see and download files that were uploaded before updating from HH1.13 to HH1.14

**HH1.14.0 + Files 0.16.1**
No change: Doesn’t work

**Comment by funkycram** [comment]
I confirm the bug

**Comment by Semir1212** [comment]
@luke- It seems to work if the file is reuploaded under the same name.

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6342.

The bug was on uploading, unfortunately the broken files should be reuploaded, because original file content was not stored.

**Comment by luke-** [comment]
Fixed with 1.14.2

**Comment by pheraph** [comment]
@yurabakhtin I am not sure if the problem is really related to this issue, but we are currently observing a very similar problem (HumHub 1.14.2, cfiles 0.16.1). It looks like it is only triggered by a certain file size (over 1 MB). When I upload a new file, an error comes when I try to call it from HumHub:

`yii\base\ErrorException: fopen(/var/www/html/humhub/uploads/file/4/7/47638bf8-224f-47b3-9402-00811f4a6bac/file): failed to open stream: No such file or directory`

In the said directory itself, there is only 1 file named `old-300` and it is in full size. After copying the file to the name `file`, it can be downloaded properly. Any ideas on this? Could this be related or should I open a new issue?

**Comment by yurabakhtin** [comment]
@pheraph Sorry for the inconvenience, but I have tested again an uploading different files with sizes less and more 1Mb on the HumHub 1.14.2 and cfiles 0.16.1, so in all cases I see a file content is uploading to a file with name `file`.
But only if I revert the fix https://github.com/humhub/humhub/pull/6342/files then yes the file with name `file` is lost, so I find only `old-123` instead.

Do you have a possibility to check your file `protected/humhub/modules/file/models/FileUpload.php` on the line 48 to be sure you have there the correct code? :

- `if (!empty($changedAttributes) && $this->uploadedFile instanceof UploadedFile) {`

and not the old wrong code:

- `if ($this->uploadedFile !== null && $this->uploadedFile instanceof UploadedFile) {`

---

If it will not help you, could you please describe step by step how you upload a file with more details, and if you can provide some screenshots, or the file which is broken on uploading if the file is not private.

Thanks.

**Comment by pheraph** [comment]
I do not have direct access to the machine, but have asked an admin to review the file and the latest patch is included (see link below). I have also provided a short screencast and an affected file here:

https://seafile.rlp.net/d/1894243ee99f496d92e0

However not much is really detectable. The only thing I can say is that a larger file size seems to be the triggering factor. However, I couldn't pinpoint a hard limit on the size either.

**Comment by pheraph** [comment]
Just want to add that the problem still appears, if a (bigger) file is uploaded via the upload button of the files module. If the same file is attached to a post it works. And if the file is stored as a zip file and upload via the Zip upload function, it works also.

**Comment by yurabakhtin** [comment]
> I do not have direct access to the machine, but have asked an admin to review the file and the latest patch is included (see link below). I have also provided a short screencast and an affected file here:
> 
> https://seafile.rlp.net/d/1894243ee99f496d92e0
> 
> However not much is really detectable. The only thing I can say is that a larger file size seems to be the triggering factor. However, I couldn't pinpoint a hard limit on the size either.
>
> Just want to add that the problem still appears, if a (bigger) file is uploaded via the upload button of the files module. If the same file is attached to a post it works. And if the file is stored as a zip file and upload via the Zip upload function, it works also.

@pheraph Hello, thank you for the provided samples, but I tested the uploading with the files and cannot reproduce this via the green uploader button from the "Files" module. Do you still have the problem?

**Comment by yurabakhtin** [comment]
Possible solution is here https://github.com/humhub/humhub-internal/issues/96#issuecomment-1669739134, waiting for response with testing.

**Comment by pheraph** [comment]
@yurabakhtin The link goes to a private repo, so I can't follow it. Anything I can do to help testing?

**Comment by yurabakhtin** [comment]
> @yurabakhtin The link goes to a private repo, so I can't follow it. Anything I can do to help testing?

@pheraph Sorry, yes the link is private.
The fix is located here https://github.com/humhub/humhub/pull/6489, it will be available in HumHub version `1.14.4`.
You can either wait the release or if you have a possibility to apply the change from the PR manually, then it would be good if you test how it works on your cases, because I could not reproduce this but I hope the fix will solves the related bugs.
Thanks.

**Comment by pheraph** [comment]
@yurabakhtin Thanks, but, well, now after a few weeks absence I tried - before applying the patch - to reproduce the problem in exactly the same instance with exactly the same file(s) and guess what: the error doesn't currently occur. I'm not sure whether to laugh or cry.

**Comment by yurabakhtin** [comment]
@pheraph Thank you for the response, ok if you will catch the error again please report here or create another issue.

**Comment by dreua** [comment]
This somehow looks like a race condition to me, if I bulk-upload 20 images (between 250 kB and 1.2MB, 10.3 MB in total), there are usually a few broken after the upload. But then again there are attempts when all go through fine. Tried to apply the fix linked above, we'll see how that goes.

Did anyone try to script something to fix the already broken uploads on the server side? (Are there instances where a `uploads/files/<x>/<y>/<guid>` directory should only contain `old-` files but no `file` file? Otherwise that should be doable with a relatively simple script, I'd probably use `find` with some lines of Python or Bash.)

For SEO: The error message is "Could not find requested file!" - I wish I found this issue here earlier and not only through the changelog. The title could be edited to contain something about "uploads", too.
